python3-pyqtchart: bump 5.15.1 -> 5.15.7
The current pyqtchart version does not build because the sip
version is not compatible, resulting in the below error:

Error: Make sure you have a working sip on your PATH or use the --sip argument

Update pyqtchart to the latest available version on PyPI and adjust
the recipe accordingly.

Signed-off-by: Christian Kohn <chris.kohn@amd.com>