nativesdk-qtbase.inc: Remove unused contents
Fixes:

ERROR: QA Issue: nativesdk-qtbase: Files/directories were installed but not shipped
  /opt/oel/13.0+snapshot/sysroots/i686-oelsdk-linux/usr/lib
  /opt/oel/13.0+snapshot/sysroots/i686-oelsdk-linux/usr/include
  /opt/oel/13.0+snapshot/sysroots/i686-oelsdk-linux/usr/share
  /opt/oel/13.0+snapshot/sysroots/i686-oelsdk-linux/usr/lib/libQt5Test.so
  /opt/oel/13.0+snapshot/sysroots/i686-oelsdk-linux/usr/lib/libQt5Network.so
  ...

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>