qtwebengine: drop 0002-chromium_overrides.cpp-Fix-build-with-plugins-and-oz.patch
* with 5.12 it looks like it's not needed anymore, it causes following error instead:
  linking ../../lib/libQt5WebEngineCore.so.5.12.0
  ../../../../git/src/3rdparty/chromium/content/browser/renderer_host/pepper/pepper_truetype_font_list_host.cc:79: error: undefined reference to 'content::GetFontFamilies_SlowBlocking(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)'
  ../../../../git/src/3rdparty/chromium/content/browser/renderer_host/pepper/pepper_truetype_font_list_host.cc:93: error: undefined reference to 'content::GetFontsInFamily_SlowBlocking(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<ppapi::proxy::SerializedTrueTypeFontDesc, std::allocator<ppapi::proxy::SerializedTrueTypeFontDesc> >*)'
  collect2: error: ld returned 1 exit status
  Makefile.core_module:74: recipe for target '../../lib/libQt5WebEngineCore.so.5.12.0' failed

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>