qtwebkit: Fix QA Warning
* there are multiple -L paths to workdir, causing QA warning like this:
  ERROR: qtwebkit-5.5.99+5.6.0-rc+gitAUTOINC+d2ff5a0855-r0 do_populate_sysroot: QA Issue: Qt5WebKit.pc failed sanity test
  (tmpdir) in path qtwebkit/5.5.99+5.6.0-rc+gitAUTOINC+d2ff5a0855-r0/sysroot-destdir//usr/lib/pkgconfig [pkgconfig]
* qtwebkit is dead, so hack it with simple sed, feel free to fix it in
  mkspecs if you want

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>