qt: remove unnecessary FILES.*-dbg variables for packaging .debug files
* package.bbclass can do it automatically since:
  commit da5ec06814e105451cca11cce76b5c5231110524
  Author: Richard Purdie <richard.purdie@linuxfoundation.org>
  Date:   Tue Dec 15 15:38:54 2015 +0000

    package: Add auto package splitting of .debug files

* .debug files for examples were incorrectly picked by qtbase-qmlplugins-dbg
  causing following QE error, because unlike qtbase-examples-dbg we don't
  have libdir in INSANE_SKIP.

  ERROR: qtbase-5.11.2+gitAUTOINC+49efea26a5-r0 do_package_qa: QA Issue: qtbase-qmlplugins-dbg: found library in wrong location: /usr/share/qt5/examples/widgets/tools/plugandpaint/plugins/.debug/libpnp_extrafilters.so
  qtbase-qmlplugins-dbg: found library in wrong location: /usr/share/qt5/examples/widgets/tools/styleplugin/styles/.debug/libsimplestyleplugin.so
  qtbase-qmlplugins-dbg: found library in wrong location: /usr/share/qt5/examples/widgets/tools/echoplugin/plugins/.debug/libechoplugin.so [libdir]
  ERROR: qtbase-5.11.2+gitAUTOINC+49efea26a5-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>