qtbase: qdbusxml2cpp: don't track command line
Fixes:
ERROR: QA Issue: File /usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/compass_interface.h in package qtsensors-src contains reference to TMPDIR [buildpaths]
ERROR: QA Issue: File /usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/sensorproxy_interface.h in package qtsensors-src contains reference to TMPDIR [buildpaths]
ERROR: QA Issue: File /usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/properties_interface.cpp in package qtsensors-src contains reference to TMPDIR [buildpaths]
ERROR: QA Issue: File /usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/properties_interface.h in package qtsensors-src contains reference to TMPDIR [buildpaths]
ERROR: QA Issue: File /usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/sensorproxy_interface.cpp in package qtsensors-src contains reference to TMPDIR [buildpaths]
ERROR: QA Issue: File /usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/compass_interface.cpp in package qtsensors-src contains reference to TMPDIR [buildpaths]

caused by this:

./qtsensors-src/usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/compass_interface.h: * Command line was: qdbusxml2cpp -N -p compass_interface.h: /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/qtsensors/5.15.16+git/git/src/plugins/sensors/iio-sensor-proxy/net.hadess.SensorProxy.Compass.xml
./qtsensors-src/usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/sensorproxy_interface.h: * Command line was: qdbusxml2cpp -N -p sensorproxy_interface.h: /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/qtsensors/5.15.16+git/git/src/plugins/sensors/iio-sensor-proxy/net.hadess.SensorProxy.xml
./qtsensors-src/usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/properties_interface.cpp: * Command line was: qdbusxml2cpp -i properties_interface.h -p :properties_interface.cpp /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/qtsensors/5.15.16+git/git/src/plugins/sensors/iio-sensor-proxy/org.freedesktop.DBus.Properties.xml
./qtsensors-src/usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/properties_interface.h: * Command line was: qdbusxml2cpp -N -p properties_interface.h: /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/qtsensors/5.15.16+git/git/src/plugins/sensors/iio-sensor-proxy/org.freedesktop.DBus.Properties.xml
./qtsensors-src/usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/sensorproxy_interface.cpp: * Command line was: qdbusxml2cpp -i sensorproxy_interface.h -p :sensorproxy_interface.cpp /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/qtsensors/5.15.16+git/git/src/plugins/sensors/iio-sensor-proxy/net.hadess.SensorProxy.xml
./qtsensors-src/usr/src/debug/qtsensors/5.15.16+git/src/plugins/sensors/iio-sensor-proxy/compass_interface.cpp: * Command line was: qdbusxml2cpp -i compass_interface.h -p :compass_interface.cpp /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/qtsensors/5.15.16+git/git/src/plugins/sensors/iio-sensor-proxy/net.hadess.SensorProxy.Compass.xml

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>