python-pyqt5, qtwebengine, qtwebkit, qt-kiosk-browser: skip without meta-python2
Neither of these actually builds with python3, skip them when
meta-python2 isn't included until real fix is available.

qtwebkit might not get the support for python3 at all

qtwebengine I have some changes for the initial build, but there
are many more needed as shown in upstream chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=942720
https://bugs.chromium.org/p/chromium/issues/list?q=label%3AProj-Python3Migration&can=2

python-pyqt5 is already blacklisted because of sip

qtwebengine with python3 shows in log.do_configure that it won't actually
build qtwebengine, but it doesn't fail. do_compile fails but with a bit
misleading error:

ERROR: qtwebengine-5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0 do_compile: oe_runmake failed
ERROR: qtwebengine-5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0 do_compile: Execution of '/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/temp/run.do_compile.16479' failed with exit code 1:
cd src/ && ( test -e Makefile || /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot-native/usr/bin/qmake -o Makefile /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/git/src/src.pro CONFIG+=force_debug_info QT_BUILD_PARTS-=examples QT_BUILD_PARTS-=tests 'QMAKE_CXX=x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot' 'QMAKE_CC=x86_64-webos-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot' 'QMAKE_LINK=x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot' 'QMAKE_CFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0=/usr/src/debug/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0                      -fdebug-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0=/usr/src/debug/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0                      -fdebug-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot-native= ' 'QMAKE_CXXFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0=/usr/src/debug/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0                      -fdebug-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0=/usr/src/debug/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0                      -fdebug-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden' -after ) && make -f Makefile
make[1]: Entering directory '/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/build/src'
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:295: recipe for target 'errorbuild' failed
make[1]: *** [errorbuild] Error 2
make[1]: Leaving directory '/home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/core2-64-webos-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/build/src'
Makefile:48: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
WARNING: exit code 1 from a shell command.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>