python-pyqt5: drop python 2 recipe
* sip-native was already removed from meta-oe and wasn't resurected in meta-python2
  so even with meta-python2 layer included this recipe cannot be built:

  ERROR: Nothing PROVIDES 'sip' (but /OE/build/oe-core/meta-qt5/recipes-python/pyqt5/python-pyqt5_5.13.2.bb DEPENDS on or otherwise requires it). Close matches:
    sip3
  ERROR: Required build target 'python-pyqt5' has no buildable providers.
  Missing or unbuildable dependency chain was: ['python-pyqt5', 'sip']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>