qtbase: fix runtime dependency on python
When running the task "do_populate_sdk()" for an image inheriting from
"populate_sdk_qt5.bbclass", the following error could be observed in
case PACKAGE_CLASSES included "package_rpm":

  ERROR: Could not invoke dnf.
  [...]
  Error:
   Problem: package packagegroup-qt5-toolchain-target-1.0-r0.noarch
            requires qtbase-mkspecs, but none of the providers can be
            installed
    - conflicting requests
    - nothing provides /usr/bin/python needed by
      qtbase-mkspecs-5.10.1+git0+6c6ace9d23-r0.armv5e

The script file in question that requires python to run is located at
"/usr/lib/qt5/mkspecs/features/uikit/devices.py".

The aforementioned dependency has been circumvented by calling python
indirectly via "/usr/bin/env".

Signed-off-by: Dennis Menschel <menschel-d@posteo.de>