qt5-demo-extrafiles: use UNPACKDIR
* fixes:
  Parsing recipes...
  ERROR: meta-qt5/recipes-qt/demo-extrafiles/qt5-demo-extrafiles.bb: Using S = ${WORKDIR} is no longer supported
  ERROR: Parsing halted due to errors, see error messages above

* see:
  https://lists.openembedded.org/g/openembedded-architecture/message/2007

* it's fatal error since:
  https://git.openembedded.org/openembedded-core/commit/?h=master&id=32cba1cc916ad530c5e6630a927e74ca6f06289b

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>