qtbase-5.0.2: Fix build without -fpermissive
* commit in newer qt is using GLint and casting to GLuint
  later so it doesn't have this issue:
  commit 1d8ec5fae2fa4bf694b93bb6bf14a7c42c84a9b6
  Author: Valery Volgutov <valery.volgutov@lge.com>
  Date:   Tue May 21 14:18:17 2013 -0700

    Fix FBO restoring in QOpenGLTextureGlyphCache

* but backport to 5.0.2 is using GLuint:
  and causes build failure without -fpermissive:
  | qtbase/5.0.2-r3/qtbase-opensource-src-5.0.2/src/gui/opengl/qopengltextureglyphcache.cpp:151:51: error: invalid conversion from 'GLuint* {aka unsigned int*}' to 'GLint* {aka int*}' [-fpermissive]
  |      glGetIntegerv(GL_FRAMEBUFFER_BINDING, &saveFbo);
  |                                                    ^
  | /usr/include/GLES2/gl2.h:536:37: error:   initializing argument 2 of 'void glGetIntegerv(GLenum, GLint*)' [-fpermissive]
  |  GL_APICALL void         GL_APIENTRY glGetIntegerv (GLenum pname, GLint* params);
  |                                      ^

* resync with version from 5.1.1 to fix this

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>