qmake5_base: delete *.la files
* they reference workdir and trip sanity check:
  ERROR: QA Issue: libQt5Sql.la failed sanity test (workdir) in path qtbase/5.5.99+5.6.0-alpha1+gitAUTOINC+f7f4dde80e-r0/sysroot-destdir//usr/lib [la]
* I'm intentionally not using remove-libtool.bbclass recently
  added to oe-core, because many people combine newer meta-qt5
  with older oe-core and can be missing this bbclass, I've
  pending patch to migrate this to remove-libtool.bbclass, will
  probably merge it after 2.1 or 2.2 release.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>