qtbase: Fix WORKDIR references in pkg-config files
* otherwise all builds fail with:
  ERROR: QA Issue: Qt5Core.pc failed sanity test (tmpdir) in path qtbase/5.5.99+5.6.0-alpha1+gitAUTOINC+f7f4dde80e-r0/sysroot-destdir//usr/lib/pkgconfig [pkgconfig]
  since oe-core insane.bbclass was fixed to properly search for tmpdir
  in all pkg-config files.
* this issue was there for long time, I've checked the build with jethro
  branch and it already has
  prefix=<TOPDIR>/tmp-glibc/sysroots/qemux86/usr
  it just wasn't detected by QA checks until now