qtbase: disable gold for all archs not just x86
* enabling xlib in x86_64 build was failing with:
  ERROR: Feature 'xcb-xlib' was enabled, but the pre-condition 'features.xlib && libs.xcb_xlib' failed.
* the root cause is linking with full path libm.so in my case:
  /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libm.so
  which with gold fails with:
  /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.3.0/ld: error: cannot open /lib/libm.so.6: No such file or directory
  /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.3.0/ld: error: cannot open /usr/lib/libmvec_nonshared.a: No such file or directory
  /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.3.0/ld: error: cannot open /lib/libmvec.so.1: No such file or directory
  collect2: error: ld returned 1 exit status
* not linking with libm at all in xcb test makes it pass, or linking
  with -lm as before works as well, but to be safe lets disable gold
  everywhere until it's resolved in upstream Qt
* also reported in the 5.12.2 upgrade PR:
  https://github.com/meta-qt5/meta-qt5/pull/181#issuecomment-484425112

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>