qtquickcontrols2: drop RPROVIDES
* causes
  ERROR: /OE/build/luneos-hardknott/webos-ports/meta-qt5/recipes-qt/qt5/qtquickcontrols2_git.bb: QA Issue: /OE/build/luneos-hardknott/webos-ports/meta-qt5/recipes-qt/qt5/qtquickcontrols2_git.bb: Variable RPROVIDES is set as not being package specific, please fix this. [pkgvarcheck]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>