qtwebkit: fix build with icu-75-1
icu-75 now requires C++17 (up from C++11) and C11 (up from C99).
https://icu.unicode.org/download/75

Fixes:
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:317:10: error: 'is_convertible_v' is not a member of 'std'; did you mean 'is_convertible'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:317:28: error: expected primary-expression before ',' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:331:13: error: 'u16string_view' in namespace 'std' does not name a type; did you mean 'u16string'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:339:13: error: 'u16string_view' in namespace 'std' does not name a type; did you mean 'u16string'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:360:36: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:360:47: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:361:13: error: 'u16string_view' in namespace 'std' does not name a type; did you mean 'u16string'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:370:36: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:370:47: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/char16ptr.h:372:13: error: 'u16string_view' in namespace 'std' does not name a type; did you mean 'u16string'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:561:26: error: parameter declared 'auto'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/stringpiece.h:134:29: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/stringpiece.h:134:40: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/stringpiece.h:185:19: error: expected type-specifier
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:346:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:346:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:381:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:381:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:1959:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:1959:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:2226:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:2226:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:2299:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:2299:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3035:19: error: expected type-specifier
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3273:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3273:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3599:40: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3599:51: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3755:60: error: 'std::u16string_view' has not been declared
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3871:64: error: 'std::u16string_view' has not been declared
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3875:32: error: 'std::u16string_view' has not been declared
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:348:10: error: 'u16string_view' is not a member of 'std'; did you mean 'u16string'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:350:46: error: 'sv' was not declared in this scope
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:1962:45: error: 'toU16StringView' is not a member of 'icu_76::internal'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:2228:31: error: 'toU16StringView' is not a member of 'icu_76::internal'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:2301:31: error: 'toU16StringView' is not a member of 'icu_76::internal'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3276:24: error: 'toU16StringViewNullable' is not a member of 'icu_76::internal'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:3601:53: error: 'toU16StringView' is not a member of 'icu_76::internal'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:4116:38: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:4116:49: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:4118:46: error: 'toU16StringView' is not a member of 'icu_76::internal'
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/unistr.h:4125:53: error: 'std::u16string_view' has not been declared
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/uset.h:1655:10: error: 'u16string_view' in namespace 'std' does not name a type; did you mean 'u16string'?
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/ucol.h:1553:25: error: 'enable_if_t' in namespace 'std' does not name a template type
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/ucol.h:1553:36: error: expected '>' before '<' token
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/ucol.h:1559:26: error: 'std::string_view' has not been declared
qtwebkit/5.15.16+git/recipe-sysroot/usr/include/unicode/ucol.h:1559:48: error: 'std::string_view' has not been declared

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>