packagegroup-qt5-toolchain-target: Use TUNE_PKGARCH instead of MACHINE_ARCH
* it was changed to MACHINE_ARCH in:
  commit 0d88f4488f08dc92081274ec954c8795d6dfe68c (marc-cpdesign/master-next, marc-cpdesign/jansa/master)
  Author: Khem Raj <raj.khem@gmail.com>
  Date:   Thu Dec 5 11:31:27 2019 -0800

    packagegroup-qt5-toolchain-target: Make machine specific

    We want to deploy arch specific overrides

    Signed-off-by: Khem Raj <raj.khem@gmail.com>

* but TUNE_PKGARCH qt5-creator has packagegroup-qt5-toolchain-target in
  RRECOMMENDS_${PN} causing:

   === Comparing signatures for task do_package_write_ipk.sigdata between tissot and mido ===
  ERROR: qt5-creator different signature for task do_package_write_ipk.sigdata between tissot and mido
  NOTE: Starting bitbake server...
  Hash for dependent task packagegroups/packagegroup-qt5-toolchain-target.bb:do_packagedata changed from f8a21ed2c484abfbadae768ec9a2e04883e80fe7ac32f7eaf442f12b4cd1b65b to bd700f438812693132a93e88c2518c81818d89856d8793b8eae479dc7a180b68
  Unable to find matching sigdata for /home/jenkins/workspace/luneos-testing/webos-ports/meta-qt5/recipes-qt/packagegroups/packagegroup-qt5-toolchain-target.bb:do_packagedata with hashes f8a21ed2c484abfbadae768ec9a2e04883e80fe7ac32f7eaf442f12b4cd1b65b or bd700f438812693132a93e88c2518c81818d89856d8793b8eae479dc7a180b68

  ERROR: 1 errors found in /home/jenkins/workspace/luneos-testing/webos-ports/tmp-glibc/sstate-diff/1579172712/signatures.mido.do_package_write_ipk.sigdata.log

* use TUNE_PKGARCH to match qt5-creator while still allowing arch
  specific overrides

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>