qt5-ptest.inc: append do_populate_sysroot only for target
* otherwise it breaks e.g. qtxmlpatterns-native build as shown in:
  http://errors.yoctoproject.org/Errors/Details/147039/

ERROR: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_populate_sysroot(d)
     0003:
File: 'TOPDIR/openembedded-core/meta/classes/staging.bbclass', lineno: 128, function: do_populate_sysroot
     0124:
     0125:python do_populate_sysroot_setscene () {
     0126:    sstate_setscene(d)
     0127:}
 *** 0128:addtask do_populate_sysroot_setscene
     0129:
     0130:def staging_copyfile(c, target, dest, postinsts, seendirs):
     0131:    import errno
     0132:
File: 'TOPDIR/openembedded-core/meta/classes/staging.bbclass', lineno: 114, function: copyFiles
     0110:
     0111:do_populate_sysroot[vardeps] += "${SYSROOT_PREPROCESS_FUNCS}"
     0112:do_populate_sysroot[vardepsexclude] += "MULTI_PROVIDER_WHITELIST"
     0113:
 *** 0114:POPULATESYSROOTDEPS = ""
     0115:POPULATESYSROOTDEPS_class-target = "virtual/${MLPREFIX}${TARGET_PREFIX}binutils:do_populate_sysroot"
     0116:POPULATESYSROOTDEPS_class-nativesdk = "virtual/${TARGET_PREFIX}binutils-crosssdk:do_populate_sysroot"
     0117:do_populate_sysroot[depends] += "${POPULATESYSROOTDEPS}"
     0118:
Exception: FileNotFoundError: [Errno 2] No such file or directory: 'TOPDIR/tmp-glibc/work/x86_64-linux/qtxmlpatterns-native/5.8.0+gitAUTOINC+9f7e01b582-r0/sysroot-destdir/usr/'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>