recipes-git: Upgrade to latest origin/stable
* qtbase: Fix undefined reference to qt_blend_argb32_on_argb32_ssse3

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>