qt5-ptest: fix build with yocto < 2.3 (pyro)
The expand parameter to DataSmart.getVar() defaults to True since
yocto 2.3 (pyro) [0]. Stable Yocto releases 2.2 (morty) and 2.1
(krogoth) had no default value. Older, now unsupported releases
defaulted to False [1] [2].

Not passing the expand parameter here means all recipes including
qt5-ptest.inc won't build with yocto 2.2 and 2.1 with this error
message:

  $ bitbake qtxmlpatterns -vfc populate_sysroot
  [...]
  ERROR: Error executing a python function in exec_python_func() autogenerated:

  The stack trace of python calls that resulted in this exception/failure was:
  File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
       0001:
   *** 0002:do_populate_sysroot(d)
       0003:
  File: '[...]/poky/meta/classes/staging.bbclass', lineno: 227, function: do_populate_sysroot
       0223:        p = p.replace("/", "_")
       0224:        with open(provdir + p, "w") as f:
       0225:            f.write(pn)
       0226:}
   *** 0227:
       0228:do_populate_sysroot[vardeps] += "${SYSROOT_PREPROCESS_FUNCS}"
       0229:do_populate_sysroot[vardepsexclude] += "MULTI_PROVIDER_WHITELIST"
       0230:
       0231:SSTATETASKS += "do_populate_sysroot"
  Exception: TypeError: getVar() missing 1 required positional argument: 'expand'

  DEBUG: Python function do_populate_sysroot finished
  ERROR: Function failed: do_populate_sysroot

Fixing this in a user layer requires duplicating the entire
do_populate_sysroot_append() in the .bbappend of all packages
including qt5-ptest.inc, i.e. currently qtdeclarative, qtquick1 and
qtxmlpatterns.

Avoid the hassle for those users by explicitly passing expand=True.

[0] http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=2631c375b8a025ee2e4329f6d93900bb7b5dadf7
[1] http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=c7610aa353e31977c099ce574acb188a3f4219e0
[2] http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=4e5e501155a21fe64a470c626b3afe6d9748308e

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>