Revert "pyqt5: Upgrade to 5.13.2"
This reverts commit 02715fff5ee26e8baa03420083f6aa60b45c13ea.

This version is too new for sip version in meta-oe/zeus:
Error: This version of PyQt5 requires sip 4.19.19 or later.

It was accidentally merged with other build fixes when re-syncing
master and zeus before 5.14 upgrade in master.

This is needed also for the newly added python-pyqtchart recipe.