conf/layer.conf: Add meta-oe to LAYERDEPENDS
Layer meta-openembedded/meta-oe provides sip. It is required to
avoid errors while building python3-pyqt5 which depends on sip,
for example:

ERROR: Required build target 'python3-pyqt5' has no buildable providers.
Missing or unbuildable dependency chain was: ['python3-pyqt5', 'sip3-native']

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Signed-off-by: Martin Jansa <martin.jansa@gmail.com>