qtmultimedia: fix conflicting declaration error
The error info is as the follow:
| In file included from /.../sysroots/fsl-imx6/usr/include/qt5/QtGui/qopengl.h:123:0,
|                  from /.../sysroots/fsl-imx6/usr/include/qt5/QtGui/qopenglshaderprogram.h:41,
|                  from /.../sysroots/fsl-imx6/usr/include/qt5/QtQuick/qsgmaterial.h:38,
|                  from /.../sysroots/fsl-imx6/usr/include/qt5/QtQuick/QSGMaterial:1,
|                  from /.../qtmultimedia/5.5.1+gitAUTOINC+0cf41ef53f-r0/git/src/plugins/videonode/imx6/qsgvivantevideomaterial.h:40,
|                  from /.../qtmultimedia/5.5.1+gitAUTOINC+0cf41ef53f-r0/git/src/plugins/videonode/imx6/qsgvivantevideomaterial.cpp:37:
| /.../sysroots/fsl-imx6/usr/include/qt5/QtGui/qopenglext.h:474:19: error: conflicting declaration 'typedef ptrdiff_t GLsizeiptr'
|  typedef ptrdiff_t GLsizeiptr;
|                    ^
| In file included from /.../qtmultimedia/5.5.1+gitAUTOINC+0cf41ef53f-r0/git/src/plugins/videonode/imx6/qsgvivantevideomaterial.cpp:34:0:
| /.../sysroots/fsl-imx6/usr/include/GLES2/gl2.h:67:25: note: previous declaration as 'typedef khronos_ssize_t GLsizeiptr'
|  typedef khronos_ssize_t GLsizeiptr;
|                          ^
| In file included from /.../sysroots/fsl-imx6/usr/include/qt5/QtGui/qopengl.h:123:0,
|                  from /.../sysroots/fsl-imx6/usr/include/qt5/QtGui/qopenglshaderprogram.h:41,
|                  from /.../sysroots/fsl-imx6/usr/include/qt5/QtQuick/qsgmaterial.h:38,
|                  from /.../sysroots/fsl-imx6/usr/include/qt5/QtQuick/QSGMaterial:1,
|                  from /.../qtmultimedia/5.5.1+gitAUTOINC+0cf41ef53f-r0/git/src/plugins/videonode/imx6/qsgvivantevideomaterial.h:40,
|                  from /.../qtmultimedia/5.5.1+gitAUTOINC+0cf41ef53f-r0/git/src/plugins/videonode/imx6/qsgvivantevideomaterial.cpp:37:
| /.../sysroots/fsl-imx6/usr/include/qt5/QtGui/qopenglext.h:475:19: error: conflicting declaration 'typedef ptrdiff_t GLintptr'
|  typedef ptrdiff_t GLintptr;
|                    ^
| In file included from /.../qtmultimedia/5.5.1+gitAUTOINC+0cf41ef53f-r0/git/src/plugins/videonode/imx6/qsgvivantevideomaterial.cpp:34:0:
| /.../sysroots/fsl-imx6/usr/include/GLES2/gl2.h:68:26: note: previous declaration as 'typedef khronos_intptr_t GLintptr'
|  typedef khronos_intptr_t GLintptr;
|                           ^

Here, use lgl2.h instead of gl2.h and gl2ext.h,
fix the "conflicting declaration" error.

Signed-off-by: Wenlin Kang <wenlin.kang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>