qtwebengine: Fix missing headers found in build with clang
Fixes
chromium/third_party/perfetto/include/perfetto/base/task_runner.h:48:55: error: unknown type name 'uint32_t'
|   virtual void PostDelayedTask(std::function<void()>, uint32_t delay_ms) = 0;

Signed-off-by: Khem Raj <raj.khem@gmail.com>