qtwebengine: remove PACKAGECONFIG for jsoncpp and protobuf
* removed in:
  commit ed0f3c2ef0f17c82f9ba1e8b687f46f468c705c7
  Author: Allan Sandfeld Jensen <allan.jensen@qt.io>
  Date:   Fri Jan 15 15:38:14 2021 +0100

    Remove configure options that doesn't work

    They are just confusing users.

* fixes:
  ERROR: Enabling/Disabling unknown feature 'webengine-system-jsoncpp'.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>