qtdeclarative: fix a buildpaths issue
Similar to the qtlocation recipe, strip out build paths from source files
to fix a do_package_qa error:

  ERROR: qtdeclarative-5.15.16+git-r0 do_package_qa: QA Issue: File
  /usr/src/debug/qtdeclarative/5.15.16+git/src/qmldevtools/qqmljsparser.cpp
  in package qtdeclarative-src contains reference to TMPDIR [buildpaths]

This seems to be the only problematic file:

  $ pwd
  .../packages-split/qtdeclarative-src
  $ grep --files-with-matches --recursive 'tmp/work/cortexa7t2hf-neon-imx-oe-linux-gnueabi'
  usr/src/debug/qtdeclarative/5.15.16+git/src/qmldevtools/qqmljsparser.cpp

Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
(cherry picked from commit 8c6f2a91e534dde4894c117acacf4099288149ce)
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>