qtwebengine: refresh the patches and upload them to meta-qt5 forks on github for maintenance
* fixes 0004-mkspecs-Allow-builds-with-libc-glibc.patch which didn't apply at all,
  because the modified mkspecs/features/configure.prf was dropped completely in:
  commit 047d61f188aae3fe3ebc689900b8a5c9fb6e901d
  Author: Michal Klocek michal.klocek@qt.io
  Date: Fri Aug 9 17:40:29 2019 +0200

  Add webengine-core feature

  The same chunk can be found in src/buildtools/config/support.pri, so I've updated
  the .patch accordingly, but haven't tried the build with musl yet.

* fixes 0023-chromium-Move-CharAllocator-definition-to-a-header-f.patch to apply
  ERROR: qtwebengine-5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0 do_patch: Command Error: 'quilt --quiltrc /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
  Applying patch 0023-chromium-Move-CharAllocator-definition-to-a-header-f.patch
  patching file chromium/cc/base/list_container_helper.cc
  Hunk #1 FAILED at 13.
  1 out of 1 hunk FAILED -- rejects in file chromium/cc/base/list_container_helper.cc
  patching file chromium/cc/base/list_container_helper.h
  Hunk #1 FAILED at 8.
  Hunk #2 succeeded at 174 with fuzz 1.
  1 out of 2 hunks FAILED -- rejects in file chromium/cc/base/list_container_helper.h
  Patch 0023-chromium-Move-CharAllocator-definition-to-a-header-f.patch does not apply (enforce with -f)
  ERROR: Logfile of failure stored in: /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/temp/log.do_patch.21067
  NOTE: recipe qtwebengine-5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0: task do_patch: Failed
  ERROR: Task (/OE/build/oe-core/meta-qt5/recipes-qt/qt5/qtwebengine_git.bb:do_patch) failed with exit code '1'

* build is still going (it will be a while on my slow builder)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>