qt5: upgrade to latest revision in 5.12
* WIP
* zlib temporarily disabled in qtbase-native, the configure fails too
  find it even when it is in RSS:
docker-shr qemux86-64@ ~/build/oe-core $ find /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0 -name zlib\*
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/git/src/3rdparty/freetype/src/gzip/zlib.h
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/git/src/3rdparty/zlib.pri
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/git/src/3rdparty/zlib
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/git/src/3rdparty/zlib/src/zlib.h
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/git/src/3rdparty/zlib_dependency.pri
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/recipe-sysroot-native/usr/lib/pkgconfig/zlib.pc
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/recipe-sysroot-native/usr/include/zlib.h
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/recipe-sysroot-native/sysroot-providers/zlib-native
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/recipe-sysroot-native/installeddeps/zlib-native
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/recipe-sysroot-native/installeddeps/zlib-native.2dcdd26b684916aff89d13cb1c919939
/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+7fc427ba23-r0/recipe-sysroot-native/installeddeps/zlib-native.complete

ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.

* fixes #136

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>