python3-pyqt5: Update to dev2008271829 snapshot
Old version no longer available:

ERROR: python3-pyqt5-5.15.1.dev2008081558-r0 do_fetch: Fetcher failure
for URL: 'https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5-5.15.1.dev2008081558.tar.gz'.
Unable to fetch URL from any source.

Signed-off-by: Daniel Gomez <daniel@qtec.com>